export const SET_FAST_SERVICES = 'SET_FAST_SERVICES';
export const SET_SERVICES_LIST = 'SET_SERVICES_LIST';
export const SET_STOCKS_LIST = 'SET_STOCKS_LIST';
export const SERVICES_SEARCH_CHANGE = 'SERVICES_SEARCH_CHANGE';
export const STOCKS_SEARCH_CHANGE = 'STOCKS_SEARCH_CHANGE';
export const CHANGE_SELLING_SERVS = 'CHANGE_SELLING_SERVS';
export const SET_CAN_SELL = 'SET_CAN_SELL';