export const STOCKS_UPDATE = 'STOCKS_UPDATE';
export const CARGOS_UPDATE = 'CARGOS_UPDATE';
export const STORES_UPDATE = 'STORES_UPDATE';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHECK_STOCK = 'CHECK_STOCK';
export const CHECK_ALL_STOCK = 'CHECK_ALL_STOCK';