export const SET_SERVICES = 'SET_SERVICES';
export const CHANGE_FILTER_SERV = 'CHANGE_FILTER_SERV';
export const SET_CURRENT_SERVICE = 'SET_CURRENT_SERVICE';
export const SET_CONSUMABLES = 'SET_CONSUMABLES';