export const CLOSE_PERSON_MODAL = 'CLOSE_PERSON_MODAL';
export const OPEN_PERSON_MODAL = 'OPEN_PERSON_MODAL';

export const SET_STUFF = 'SET_STUFF';
export const SET_CURRENT_USER  = 'SET_CURRENT_USER';
export const FETCHING_USER_DATA = 'FETCHING_USER_DATA';
export const SET_EMPTY_USER = 'SET_EMPTY_USER';

export const CHANGE_BLOCK_STATUS = 'CHANGE_BLOCK_STATUS';