export const CLOSE_PERSON_MODAL = 'CLOSE_PERSON_MODAL';
export const OPEN_PERSON_MODAL = 'OPEN_PERSON_MODAL';

export const SET_STUFF = 'SET_STUFF';
export const SET_CURRENT_USER  = 'SET_CURRENT_USER';