export const SET_USERS = 'SET_USERS';
export const SET_CURRENT_USER  = 'SET_CURRENT_USER';
export const SET_RANKS  = 'SET_RANKS';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const SET_EMPTY_USER = 'SET_EMPTY_USER';
export const DEL_CURRENT_USER = 'DEL_CURRENT_USER';
export const SET_USERS_FILTER = 'SET_USERS_FILTER';

export const CHANGE_BLOCK_STATUS = 'CHANGE_BLOCK_STATUS';