export const POST = "POST";
export const GET = "GET";

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GOOD_LOGIN_ERROR = 'GOOD_LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const PERMISSIONS_SUCCESS = 'PERMISSIONS_SUCCESS';
export const TOKEN_FOUND = 'TOKEN_FOUND';
export const TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const SET_ACTIVE_MIGRATION = 'SET_ACTIVE_MIGRATION';

export const NEW_PASSWORD_ACCEPTED = "NEW_PASSWORD_ACCEPTED";
export const EMAIL_ACCEPTED = "EMAIL_ACCEPTED";
export const SET_CURRENT_STORE_ID = 'SET_CURRENT_STORE_ID';
