export const PERMISSIONS = {
    OWNER: 0,
    STORE_MANAGER: 1,
    WAREHOUSE_MANAGER: 2,
    TOP_MANAGER: 3,
};

export const SERVER_STATUS = {
    OK: 200,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    NO_CONNECTION: 600
};